changes2
toptechschool123/GitHub_TestAutomation_Project pull request #1
Opened 2024-03-15 23:23 UTC by sayedsa

please review my code:

2024-03-15 23:33 UTC, toptechschool123 requested changes

2024-03-15 23:33 UTC, toptechschool123 commented on src/test/java/java/JavaCoding.java
> +		System.out.println("hi it is test 1");
please use upper case letter here. dddd

2024-03-15 23:54 UTC, sayedsa commented on src/test/java/java/JavaCoding.java
> +		System.out.println("hi it is test 1");
changes made , please review again.

2024-03-16 00:11 UTC, toptechschool123 approved these changes

2024-03-16 00:11 UTC, merged

2024-03-16 00:11 UTC, toptechschool123 commented
looks good